version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.turgotchat.fr
    depends_on:
      - backend

  backend:
    build: ./backend
    network_mode: "host"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - REDIS_URL=redis://localhost:6379
    volumes:
      - ./backend/logs:/app/logs
      - ./database/chroma_db:/app/database/chroma_db
      - ./database/last_update.txt:/app/database/last_update.txt
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped 

  db_updater:
    build: ./database
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./database/chroma_db:/app/database/chroma_db
      - ./database/data:/app/database/data
      - ./database/last_update.txt:/app/database/last_update.txt
    # Do not auto-run; we'll call it on-demand via cron
    restart: "no"